---
name: Super-Linter

on:  # yamllint disable-line rule:truthy
  push:
    branches: [prod, preprod]
  pull_request:
    branches: [prod, preprod]
permissions: read-all

jobs:
  build:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.0.0  # x-release-please-version
        env:
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
